#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    links:
       - redis:redis
    expose:
       - 8000
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000

  redis:
    image: redis
    expose:
       - 6379
  nginx:
    restart: always
    build: ./nginx/
    depends_on:
       - web
    ports:
       - "80:80"
       - "443:443"
    volumes:
       - ./mysite/static:/static
       - ./mysite/media:/media
    links:
       - web:web
