# Generated by Django 3.0.6 on 2020-05-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfficient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='x-ckr', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
