# Generated by Django 3.0.6 on 2020-05-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfficient', '0002_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
