# Generated by Django 3.0.6 on 2020-05-07 06:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodfficient', '0002_auto_20200506_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Dairy Free'), (2, 'Gluten Free'), (3, 'Keto'), (4, 'Vegan'), (5, 'Vegetarian')], max_length=9),
        ),
    ]
